server:
  port: 8081
  servlet:
    context-path: /user
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_db
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

